"""A small, reproducible binary organogram and its bounded active working set.

This is an explicit demonstration grammar, not an implementation of every f8,
Lie, or geometric operation in the source specification.  A path's depth is its
log radius, with log base 2 by demo convention.  The prior packed output selects
the next phase-table row, making the derivation self-referential.

Only active nodes are capacity bounded.  The eviction ledger is diagnostic
history and consumes additional, unbounded memory.  Original measurements are
managed separately by the runtime and cannot be regenerated by this grammar.
"""

from collections import OrderedDict
from dataclasses import dataclass
from typing import Any

from .rp32 import pack, pair, step, unpack


WORLD_VERSION = "binary-organogram-v1"
MAX_DEPTH = 32
LOG_RADIUS_BASE = 2
_CONFIG_FIELDS = {
    "seed", "phase_turns", "field_changes", "max_depth", "version", "baseline_id"
}


def _integer(value: Any, name: str) -> int:
    if type(value) is not int:
        raise ValueError(f"{name} must be an integer (not bool)")
    return value


def _capacity(value: Any) -> int:
    _integer(value, "capacity")
    if value < 1:
        raise ValueError("capacity must be at least 1")
    return value


def _path(value: Any, max_depth: int) -> str:
    if type(value) is not str:
        raise ValueError("path must be a string")
    if len(value) > max_depth or any(char not in "01" for char in value):
        raise ValueError(f"path must contain only 0 and 1 with length <= {max_depth}")
    return value


@dataclass(frozen=True)
class WorldConfig:
    """Complete derivation inputs; depth is limited to 32 for bounded decoding."""

    seed: tuple[int, int, int, int] = (250, 3, 20, 2)
    phase_turns: tuple[tuple[int, int], ...] = (
        (11, 53), (29, 83), (47, 101), (71, 137)
    )
    field_changes: tuple[int, int] = (-3, 4)
    max_depth: int = 8
    version: str = WORLD_VERSION
    baseline_id: str = "colony-baseline-v1"

    def __post_init__(self) -> None:
        if type(self.seed) is not tuple or len(self.seed) != 4:
            raise ValueError("seed must be a tuple of four RP32 lanes")
        for index, value in enumerate(self.seed):
            _integer(value, f"seed[{index}]")
            lower, upper = ((-128, 127) if index == 2 else
                            (0, 127) if index == 3 else (0, 255))
            if not lower <= value <= upper:
                raise ValueError(f"seed[{index}] must be between {lower} and {upper}")
        if type(self.phase_turns) is not tuple or len(self.phase_turns) != 4:
            raise ValueError("phase_turns must be a tuple of four pairs")
        for row in self.phase_turns:
            if type(row) is not tuple or len(row) != 2:
                raise ValueError("each phase_turns row must be a tuple of two integers")
            for value in row:
                _integer(value, "phase_turns entry")
                if not 0 <= value <= 255:
                    raise ValueError("phase_turns entries must be between 0 and 255")
        if type(self.field_changes) is not tuple or len(self.field_changes) != 2:
            raise ValueError("field_changes must be a tuple of two integers")
        for value in self.field_changes:
            _integer(value, "field_changes entry")
        _integer(self.max_depth, "max_depth")
        if not 0 <= self.max_depth <= MAX_DEPTH:
            raise ValueError(f"max_depth must be between 0 and {MAX_DEPTH}")
        if type(self.version) is not str or self.version != WORLD_VERSION:
            raise ValueError(f"unsupported world version: {self.version!r}")
        if type(self.baseline_id) is not str or not self.baseline_id.strip():
            raise ValueError("baseline_id must be a nonempty string")

    def to_dict(self) -> dict[str, Any]:
        """Return the complete configuration using only JSON-native values."""
        return {
            "seed": list(self.seed),
            "phase_turns": [list(row) for row in self.phase_turns],
            "field_changes": list(self.field_changes),
            "max_depth": self.max_depth,
            "version": self.version,
            "baseline_id": self.baseline_id,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "WorldConfig":
        """Decode an exact JSON shape; unknown fields and versions are errors."""
        if type(data) is not dict or set(data) != _CONFIG_FIELDS:
            raise ValueError("world configuration must contain exactly the six declared fields")
        if type(data["seed"]) is not list or len(data["seed"]) != 4:
            raise ValueError("seed must be a JSON array of four lanes")
        if type(data["phase_turns"]) is not list or len(data["phase_turns"]) != 4:
            raise ValueError("phase_turns must be a JSON array of four pairs")
        if any(type(row) is not list or len(row) != 2 for row in data["phase_turns"]):
            raise ValueError("phase_turns rows must be JSON arrays of two integers")
        if type(data["field_changes"]) is not list or len(data["field_changes"]) != 2:
            raise ValueError("field_changes must be a JSON array of two integers")
        return cls(
            seed=tuple(data["seed"]),
            phase_turns=tuple(tuple(row) for row in data["phase_turns"]),
            field_changes=tuple(data["field_changes"]),
            max_depth=data["max_depth"],
            version=data["version"],
            baseline_id=data["baseline_id"],
        )


@dataclass(frozen=True)
class Node:
    path: str
    pair: int
    log_radius: int

    def as_dict(self) -> dict[str, Any]:
        return {"path": self.path, "pair": self.pair, "log_radius": self.log_radius}


class World:
    """Pure reconstruction plus a FIFO active cache containing atomic pairs.

    Cache hits do not change insertion order.  ``regeneration_count`` counts
    cache misses for paths that were previously evicted, excluding their first
    materialization.  Direct calls to ``derive`` never alter cache or counters.
    """

    def __init__(self, config: WorldConfig, capacity: int):
        if type(config) is not WorldConfig:
            raise ValueError("config must be a WorldConfig")
        self._config = config
        self._capacity = _capacity(capacity)
        self._active: OrderedDict[str, Node] = OrderedDict()
        self._evicted: list[str] = []
        self._hits = 0
        self._regenerations = 0

    @property
    def config(self) -> WorldConfig:
        return self._config

    @property
    def capacity(self) -> int:
        return self._capacity

    @property
    def active_paths(self) -> tuple[str, ...]:
        return tuple(self._active)

    @property
    def evicted_paths(self) -> tuple[str, ...]:
        return tuple(self._evicted)

    @property
    def hit_count(self) -> int:
        return self._hits

    @property
    def regeneration_count(self) -> int:
        return self._regenerations

    def derive(self, path: str) -> Node:
        """Reconstruct a node solely from the baseline, rules, and binary path."""
        _path(path, self.config.max_depth)
        word = pack(*self.config.seed)
        for character in path:
            branch = int(character)
            r, g, b, _ = unpack(word)
            row = (g ^ (r >> 6)) & 3
            moved = step(word, self.config.phase_turns[row][branch])
            next_r, _, _, next_a = unpack(moved)
            next_g = (3 * g + branch + 1) % 256
            next_b = max(-128, min(127, b + self.config.field_changes[branch]))
            word = pack(next_r, next_g, next_b, (next_a & ~7) | 2)
        return Node(path=path, pair=pair(word), log_radius=len(path))

    def get(self, path: str) -> Node:
        _path(path, self.config.max_depth)
        if path in self._active:
            self._hits += 1
            return self._active[path]
        node = self.derive(path)
        if path in self._evicted:
            self._regenerations += 1
        self._active[path] = node
        self._evict_overflow()
        return node

    def resize(self, capacity: int) -> None:
        """Set active capacity, evicting oldest insertions immediately if needed."""
        self._capacity = _capacity(capacity)
        self._evict_overflow()

    def _evict_overflow(self) -> None:
        while len(self._active) > self._capacity:
            path, _ = self._active.popitem(last=False)
            self._evicted.append(path)
